---
- hosts: all
  connection: local
  module_defaults:
    apt:
      cache_valid_time: 3600
  pre_tasks:
    - name: Gather the package facts
      package_facts:
        manager: apt
      tags:
        - packages
  roles:
    - basic-tools
    - docker
    - fortune
    - git
    - wireguard
