- name: Install basic tools
  become: yes
  apt:
    state: latest
    name:
    - curl
    - jq
    - htop
    - mc
    - ncdu
    - tmux
    - zip
    - bat
    - screen
    - vim
    - fzf
  tags:
    - packages
    - shell
