- name: Install basic tools
  become: yes
  apt:
    state: latest
    name:
    - bat
    - curl
    - fzf
    - htop
    - jq
    - mc
    - ncdu
    - screen
    - tmux
    - vim
    - zip
    - zsh
  tags:
    - packages
    - shell
