- name: "Install docker and docker-compose"
  tags:
    - packages
    - docker
  block:
  - name: Install docker and supporting tools
    apt:
      name: ['docker.io']
      state: latest
    become: yes

  - name: Add "{{ansible_env.USER}}" user to docker group
    user:
      name: "{{ansible_env.USER}}"
      groups: docker
      append: yes
    become: yes
